version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building the project and skipping tests...
      - mvn clean package -DskipTests=true
artifacts:
  files:
    - target/AWS-Deploy-Employee.jar
  discard-paths: yes
