version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - mvn --version

  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean package -DskipTests=true
      - echo "Listing target folder"
      - ls -alh target

artifacts:
  files:
    - target/AWS-Deploy-Employee.jar
  discard-paths: yes
