version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn -version
  build:
    commands:
      - echo Packaging JAR without tests...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/AWS-Deploy-Employee.jar
  discard-paths: yes
